### ISSUE TITLE
credits.txt location

### ISSUE THREAD

**Issue by mnot** [kemitchell/creditstxt.com#5]
This text on the site:

> Serve credits.txt as a UTF-8-encoded, plain-text file at /credits.txt

can be read to imply that credits are *always* found at that location. This violates [BCP190](https://tools.ietf.org/html/bcp190) -- basically, it's squatting on space that the Web site might want to use for something else.

Two possible ways forward:

* [ ] Use `/.well-known/credits.txt` -- see [RFC5785bis](https://mnot.github.io/I-D/rfc5785bis/) (currently [in the RFC Editor Queue](https://datatracker.ietf.org/doc/draft-nottingham-rfc5785bis/)
* [ ] Clarify that that location is just an example, and the normative way to find credits is using a link relation.

**Comment by kemitchell** [comment]
@mnot, thank you for this feedback.

I would have to go back to reread BCP190 to respond in those terms. Without doing so, I'll share a few points that come to mind, in my own words:

First, `credits.txt` isn't about networking or software automation, but content. We advocate that web masters choose `credits.txt` for content about credits.

Second, `/.well-known/` is not well known, even among developers.  I personally associate it with resources to be consumed by software, rather than people.  Scripts for fetching Let's Encrypt certificates use it, for example.

Third, browsing `link` relations is not straightforward in web browsers, and it will not be apparent that such relations exist to non-technical people.

Overall, I'm very excited to give `credits.txt` structure, through standards processes and otherwise. But the appeal of `credits.txt` is not to technical correctness, compliance, or interoperability. It's a basic ethical matter.  Developers and other creditors to websites, especially those who contribute work for free, deserve recognition at least akin to that afforded contributors in other media.

**Comment by doriantaylor** [comment]
I was going to suggest at one point a machine-readable variant accessible through content negotiation but didn't want to jump the gun…

**Comment by kemitchell** [comment]
@doriantaylor not against that at all! If you've got the energy, go for it!

I speak only for myself when I say that I'm worried about giving myself too much to do on this in a technical vein. In my experience, I'll use the jollies I get from over-specifying and achieving small things on my own to ignore the harder problems around socialization and acceptance.

**Comment by mnot** [comment]
BCP190 isn't about how structured the data is; it's about whether you (or anyone else) has the right to claim space on other people's Web servers by writing specs like this.

It establishes that as a bad practice, and  reserves `/.well-known` as an escape valve for applications like yours. They're used by lots of folks, like [Apple](https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html), [Let's Encrypt](https://letsencrypt.org/how-it-works/), [KeyBase](https://keybase.io/docs/keybase_well_known), [OpenID](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig) and lots of others.

**Comment by kemitchell** [comment]
@mnot I don't think this is an application, or a spec. What we're trying to build is a social norm and a professional obligation that affects the content of websites.

Compare to film credits. They aren't a part of the DVD standard, like subtitles or chapter markers, though they appear on nearly every mass-produced DVD. They _are_ a norm in the film industry, and a requirement of many union and private agreements on the production side.

**Comment by doriantaylor** [comment]
How does BCP190 square with `robots.txt`? or is that considered grandfathered? (also [`humans.txt`](http://humanstxt.org/)?)

What about specifying `/.well-known/credits.txt` with I dunno, an exhortation to alias it to `/credits.txt` at the discretion of the site owner?

**Comment by doriantaylor** [comment]
Trudging through logs on my own stuff here, noticed:

* Requests to `/.well-known/security.txt` and [attendant I-D](https://tools.ietf.org/html/draft-foudil-securitytxt-06)
* Requests to `/ads.txt` and [attendant _not_ I-D](https://iabtechlab.com/wp-content/uploads/2019/03/IAB-OpenRTB-Ads.txt-Public-Spec-1.0.2.pdf)

One of these is compliant with BCP190, the other is not. One is esoteric, while the other [enjoys considerable adoption](https://en.wikipedia.org/wiki/Ads.txt#State_of_adoption). Obviously there are a number of reasons why one of these schemes is going to get more attention than another, and I am willing to assume for the sake of argument that the location of the resource is low on the list. However, if the location contributes at all to adoption I don't think it hurts to have the spec say something like:

* **SHOULD**  be located at `/.well-known/credits.txt`
* **MAY** be located at `/credits.txt`

**Comment by kemitchell** [comment]
Agreed.
